compact: false

controlFlowFlattening: false

deadCodeInjection: false

debugProtection: false

disableConsoleOutput: false

domainLock:
  - .moegirl.org.cn

domainLockRedirectUrl: https://zh.moegirl.org.cn/Mainpage

identifierNamesGenerator: hexadecimal

log: true

numbersToExpressions: false

simplify: false

splitStrings: true

splitStringsChunkLength: 7

stringArray: true

stringArrayCallsTransform: false

stringArrayCallsTransformThreshold: 1

stringArrayEncoding:
  - base64

stringArrayIndexShift: true

stringArrayRotate: true

stringArrayShuffle: true

stringArrayWrappersCount: 1

stringArrayWrappersChainedCalls: false

stringArrayWrappersParametersMaxCount: 3

stringArrayWrappersType: function

stringArrayThreshold: 1

target: browser-no-eval

transformObjectKeys: true
