name: post commit CI

on:
  push:
    paths:
      - "scripts/**/*.js"
      - ".github/workflows/postCommit.yml"
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

concurrency: postCommit

jobs:
  postCommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
          cache: npm
      - uses: technote-space/get-diff-action@v6
        name: List diff
      - name: Install dependencies
        run: npm ci
      - name: Auto browserify generator
        run: node scripts/browserify/index.js
      - name: Auto prefetch
        run: node scripts/prefetch/index.js
      - name: Gadget-polyfill generator
        run: node scripts/generatePolyfill/index.js
      - name: Gadgets-definition Generator
        run: node scripts/gadgetsDefinitionGenerator/index.js
      - name: Conventional Commits scopes generator
        run: node scripts/conventionalCommitsScopesGenerator/index.js
      - uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          committer_email: actions@github.com
          default_author: github_actor
          message: "auto: post Commit CI - commit from GitHub Actions"
          push: false
      - name: Show git status & push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node scripts/postCommit/push.js
